variables:
    CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  
  before_script:
    - docker login -u $CI_ACCESS_USER -p $CI_ACCESS_TOKEN $CI_REGISTRY
  
  services:
    - docker:dind
  
  stages:
    - build
  
  build:
    stage: build
    script:
      - docker build --rm -t $CONTAINER_IMAGE .
      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
      - docker push $CONTAINER_IMAGE
    tags:
      - docker