variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

image: gitlab/dind

services:
  - docker:dind

before_script:
  - docker login -u $CI_ACCESS_USER -p $CI_ACCESS_TOKEN $CI_REGISTRY
  
stages:
  - build
  
build:
  stage: build
  script:
    - docker build --rm -t $CONTAINER_IMAGE .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CONTAINER_IMAGE
  tags:
    - docker
