name: Compile Plugin

on:
  push:
    branches: 
      - master
      - dev/*
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sm_version: ["1.10", "1.11"]
    
    steps:
      - uses: actions/checkout@v1

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION }}

      - name: Download Multicolors
        run: |
          mkdir dependency
          cd dependency
          git clone https://github.com/Bara/Multi-Colors.git .
          rsync -av addons/sourcemod/scripting/include/ $includePath
          rm -rf dependency
      
      - name: Compile Plugin
        run: spcomp -E -v2 -i $includePath addons/sourcemod/scripting/1v100.sp
